update tool

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,3 +1,7 @@
+# This workflow is to automatically publish and tag packages
+#
+# It waits until all other ci tasks to pass before running the critical section.
+
 name: release
 on:
   push:
@@ -9,31 +13,8 @@ jobs:
     name: release
     runs-on: ubuntu-latest
     steps:
-      - name: Wait on tests
-        uses: lewagon/wait-on-check-action@master
-        with:
-          ref: ${{ github.sha }} # can be commit SHA or tag too
-          running-workflow-name: 'release'
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          wait-interval: 10 # seconds
-      - name: Wait on last commit
-        uses: lewagon/wait-on-check-action@master
-        with:
-          ref: ${{ github.sha }}~ # can be commit SHA or tag too
-          check-name: 'release'
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          wait-interval: 10 # seconds
-          # Github actions does not have a re-run flag, so we can't skip this wait for re-run,
-          # In order to not get stuck into a failure loop, we allow failure conclusion for this wait.
-          allowed-conclusions: success,skipped,cancelled,failure
-      # Checks out a copy of your repository on the ubuntu-latest machine
-      - name: Checkout code
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
-        with:
-          fetch-depth: 0 #fetch all history so the tool can get all the tag to determine version.
-
       - name: "Install Flutter"
-        # Github aciont doesn't support templates so it is hard to share this snippet with another action
+        # Github Actions don't support templates so it is hard to share this snippet with another action
         # If we eventually need to use this in more workflow, we could create a shell script that contains this
         # snippet.
         run: |
@@ -43,35 +24,70 @@ jobs:
           echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
           echo "$HOME/_flutter/.pub-cache/bin" >> $GITHUB_PATH
           echo "$HOME/_flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
+          flutter doctor -v
           cd $GITHUB_WORKSPACE
+      - name: Set up tools
+        run: dart pub get
+        working-directory: ${{ github.workspace }}/plugins/script/tool
+      - name: Get publish check status
+        run: |
+          export PUBLISH_CHECK_JSON=$(dart ./script/tool/lib/src/main.dart publish-check --machine)
+          echo "The PUBLISH_CHECK_JSON is: " + $PUBLISH_CHECK_JSON
+          export PUBLISH_CHECK_STATUS=$(dart ./script/tool/lib/src/main.dart read-map-json --json "$PUBLISH_CHECK_JSON" --key "status")
+          echo "The PUBLISH_CHECK_STATUS is: " + $PUBLISH_CHECK_STATUS
+        working-directory: ${{ github.workspace }}/plugins
+      - name: Cancel if PUBLISH_CHECK_STATUS no-publish
+        # Prints the status, all the steps after this only runs if PUBLISH_CHECK_STATUS == 'needs-publish'
+        run: echo "The plugins updated in this commit have already been published."
+        if: ${{ PUBLISH_CHECK_STATUS == 'no-publish' }}
+      - name: Report failure if PUBLISH_CHECK_STATUS error
+        # Prints the status, all the steps after this only runs if PUBLISH_CHECK_STATUS == 'needs-publish'
+        run: |
+          echo "There's an error occured in `publish-check`, please find the details in the "Get publish check status" step"
+          exit 1
+        if: ${{ PUBLISH_CHECK_STATUS == 'error' }}
 
-      - name: flutter doctor
-        run: flutter doctor -v
-      - name: git config user.name
-        run: git config --global user.name ${{ secrets.USER_NAME }}
-      - name: git config user.email
-        run: git config --global user.email ${{ secrets.USER_EMAIL }}
+# ######################################################################################### #
+# All the steps below must be run with `if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}` #
+# ######################################################################################### #
+
+      # This workflow should be the last to run. So wait for all the other tests to succeed.
+      - name: Wait on all tests
+        uses: lewagon/wait-on-check-action@1b1630e169116b58a4b933d5ad7effc46d3d312d
+        with:
+          ref: ${{ github.sha }} # can be commit SHA or tag too
+          running-workflow-name: 'release'
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          wait-interval: 10 # seconds
+          allowed-conclusions: success
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
+
+      # The release process should be synchronized to avoid child commit release before the parent commit,
+      # which might cause issue when child commit and parent commit both contain version updates for the same
+      # plugin.
+      - name: Wait on "release" workflow at last commit
+        uses: lewagon/wait-on-check-action@1b1630e169116b58a4b933d5ad7effc46d3d312d
+        with:
+          ref: ${{ github.sha }}~ # can be commit SHA or tag too
+          check-name: 'release'
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          wait-interval: 10 # seconds
+          # TODO(cyanglaz), only allow success and skipped after https://github.com/flutter/plugins/pull/3840 lands and correct configurations added to this workflow.
+          # https://github.com/flutter/flutter/issues/81444
+          allowed-conclusions: success,skipped,cancelled,failure
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
+
+      # Checks out a copy of the repo.
+      - name: Checkout code
+        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
+        with:
+          fetch-depth: 0 # Fetch all history so the tool can get all the tag to determine version.
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
+
+      # TODO(cyanglaz): add real publish command.
       - name: run release
         run: echo "replace this command with release command"
-      - name: sleep
-        run: sleep 30
-
-
-      # - name: "Bootstrap Workspace"
-      #   run: melos bootstrap --ignore="*example*"
-      # - name: Melos Version
-      #   run: melos version --yes
-      # - name : log
-      #   run: git log
-      # - name: git push
-      #   run: git push --follow-tags
-
-      # - name: Create Pull Request
-      #   uses: peter-evans/create-pull-request@v3
-      #   with:
-      #     branch-suffix: release-packages
-      #     delete-branch: true
-      #     title: 'chore(release): publish packages'
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
 
         env:
           DEFAULT_BRANCH: master
